### ISSUE TITLE
Translation in Java

### ISSUE THREAD

**Issue by varunmaini** [PkmX/lcamera#132]
Hi, I tried your sample and it works really well. However, was wondering if there is any plan to move the project to a pure Java code ? As I think Java is much more widely used language by Android developers so that might enable them to understand and use the sample better.

**Comment by PkmX** [comment]
Unfortunately I think the project has way too many dependencies on Scala right now, so a translation to Java would pretty much require a complete rewrite.

I personally also would much prefer to work with Scala rather than Java because of its much better type system and functional language features, and so far I think Scala (and `scala.rx`) has mostly managed to keep the complicated interactions between the `camera2` API and the UI under control. (TBH I'm kind of surprised that the whole source code including UI is still just barely above 1K lines of code!)
