### ISSUE TITLE
Add a second apk just to collect information

### ISSUE THREAD

**Issue by sudoeste** [PkmX/lcamera#49]
I asked a user running the Moto g soak test to try the app and it also crashed. 

Maybe it would be helpful for you to release an apk that just dumps the camera data so you could build a database. 

Or even another very simple apk without raw support and other bells and whistles, just jpeg with manual shutter and iso to test other devices. This way you could find if there are phones with limited support for some of the functions

**Comment by sandys** [comment]
+1 from me as well.

I think some of the other phones (like the LG G2) are getting newer firmware and this app is a good way to test what capabilities are exposed by the drivers (front and back) so that we can start development.

Not everyone has access to the early updates, so this app and the information it collects will be invaluable.

**Comment by PkmX** [comment]
Closing as `adb shell dumpsys media.camera` handles this job well.

**Comment by vishesh29** [comment]
Hey man!

Love your work!!!

I've been using lcamera on my Nexus 6 and its magic!!!

Thank you so much!!!

Can you tell me how we can record slow motion with Nexus 6? And when is the
next update coming?
